import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:confetti/confetti.dart';
import '../core/app_colors.dart';

class ImageCombineAnimation extends StatefulWidget {
  final String imageAsset;

  /// Base64 data-uri strings for the unique-per-pair halves generated by the
  /// backend (e.g. "data:image/png;base64,..."). When both are provided they
  /// take priority over [imageAsset], so each pair reveals their own picture
  /// instead of the same generic one.
  final String? leftImageDataUri;
  final String? rightImageDataUri;

  final VoidCallback? onAnimationComplete;

  const ImageCombineAnimation({
    super.key,
    this.imageAsset = 'assets/images/puzzle_landscape.png',
    this.leftImageDataUri,
    this.rightImageDataUri,
    this.onAnimationComplete,
  });

  @override
  State<ImageCombineAnimation> createState() => _ImageCombineAnimationState();
}

class _ImageCombineAnimationState extends State<ImageCombineAnimation>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _slideAnimation;
  late Animation<double> _scaleAnimation;
  late Animation<double> _glowAnimation;
  late ConfettiController _confettiController;

  Uint8List? _leftBytes;
  Uint8List? _rightBytes;

  /// Data-uris look like "data:image/png;base64,AAAA..." — strip the prefix
  /// before decoding.
  Uint8List? _decodeDataUri(String? dataUri) {
    if (dataUri == null || dataUri.isEmpty) return null;
    try {
      final commaIndex = dataUri.indexOf(',');
      final base64Part = commaIndex != -1 ? dataUri.substring(commaIndex + 1) : dataUri;
      return base64Decode(base64Part);
    } catch (_) {
      return null;
    }
  }

  @override
  void initState() {
    super.initState();
    _leftBytes = _decodeDataUri(widget.leftImageDataUri);
    _rightBytes = _decodeDataUri(widget.rightImageDataUri);
    _confettiController =
        ConfettiController(duration: const Duration(seconds: 3));

    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1400),
    );

    _slideAnimation = Tween<double>(begin: 80.0, end: 0.0).animate(
      CurvedAnimation(
        parent: _controller,
        curve: const Interval(0.0, 0.65, curve: Curves.easeOutBack),
      ),
    );

    _scaleAnimation = TweenSequence<double>([
      TweenSequenceItem(tween: Tween<double>(begin: 0.9, end: 1.1), weight: 50),
      TweenSequenceItem(tween: Tween<double>(begin: 1.1, end: 1.0), weight: 50),
    ]).animate(
      CurvedAnimation(
        parent: _controller,
        curve: const Interval(0.6, 1.0, curve: Curves.easeInOut),
      ),
    );

    _glowAnimation = Tween<double>(begin: 0.0, end: 24.0).animate(
      CurvedAnimation(
        parent: _controller,
        curve: const Interval(0.65, 1.0, curve: Curves.easeOut),
      ),
    );

    _controller.forward().then((_) {
      _confettiController.play();
      if (widget.onAnimationComplete != null) {
        widget.onAnimationComplete!();
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    _confettiController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.center,
      children: [
        // Confetti explosion behind/around image
        ConfettiWidget(
          confettiController: _confettiController,
          blastDirectionality: BlastDirectionality.explosive,
          shouldLoop: false,
          colors: const [
            AppColors.primary,
            AppColors.orange,
            AppColors.green,
            Colors.yellow,
            Colors.amber,
          ],
        ),

        AnimatedBuilder(
          animation: _controller,
          builder: (context, child) {
            final double offset = _slideAnimation.value;
            final double glow = _glowAnimation.value;
            final double scale = _scaleAnimation.value;

            return Transform.scale(
              scale: scale,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(20),
                  boxShadow: [
                    BoxShadow(
                      color: AppColors.primary.withValues(alpha: glow > 0 ? 0.35 : 0.1),
                      blurRadius: glow + 12,
                      spreadRadius: glow / 3,
                    ),
                  ],
                ),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(20),
                  child: SizedBox(
                    width: 240,
                    height: 240,
                    child: Row(
                      children: [
                        // Left Image Half
                        Expanded(
                          child: Transform.translate(
                            offset: Offset(-offset, 0),
                            child: _leftBytes != null
                                // Already a standalone half-image from the backend
                                // (unique to this pair) — render it as-is.
                                ? Image.memory(
                                    _leftBytes!,
                                    width: 120,
                                    height: 240,
                                    fit: BoxFit.cover,
                                  )
                                // Fallback: crop the left half out of the shared
                                // bundled asset (used if the server didn't send
                                // per-pair images, e.g. offline/demo mode).
                                : ClipRect(
                                    child: Align(
                                      alignment: Alignment.centerLeft,
                                      widthFactor: 0.5,
                                      child: Image.asset(
                                        widget.imageAsset,
                                        width: 240,
                                        height: 240,
                                        fit: BoxFit.cover,
                                      ),
                                    ),
                                  ),
                          ),
                        ),

                        // Right Image Half
                        Expanded(
                          child: Transform.translate(
                            offset: Offset(offset, 0),
                            child: _rightBytes != null
                                ? Image.memory(
                                    _rightBytes!,
                                    width: 120,
                                    height: 240,
                                    fit: BoxFit.cover,
                                  )
                                : ClipRect(
                                    child: Align(
                                      alignment: Alignment.centerRight,
                                      widthFactor: 0.5,
                                      child: Image.asset(
                                        widget.imageAsset,
                                        width: 240,
                                        height: 240,
                                        fit: BoxFit.cover,
                                      ),
                                    ),
                                  ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      ],
    );
  }
}